@startuml
[Application] <<ConsoleApp.Application.*>>
[Infrastructure] <<ConsoleApp.Infrastructure.*>>
[Domain] <<ConsoleApp.Domain.*>>

[Application] --> [Domain]
[Infrastructure] --> [Domain]
[Infrastructure] --> [Application]

@enduml